package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strconv"
	"testing"
)

// TestPlainScalarsMatchPyYAML is the differential test that keeps this tool and
// the vault's primary Python validator from drifting apart about what a bare
// word in frontmatter means.
//
// testdata/pyyaml_scalars.json is generated by feeding each token to the
// vault's own loader (scripts/_vault.py FrontmatterLoader, i.e. PyYAML with the
// timestamp resolver removed) and recording what it produced. If this test
// fails, the two validators now disagree about a value, and a vault will pass
// or fail depending on which one happened to run — fix the resolver rather than
// the fixture, unless the Python side deliberately changed too.
func TestPlainScalarsMatchPyYAML(t *testing.T) {
	raw, err := os.ReadFile("testdata/pyyaml_scalars.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Token string `json:"token"`
		Kind  string `json:"kind"`
		Value string `json:"value"`
	}
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) < 50 {
		t.Fatalf("fixture has only %d tokens — it is meant to be a broad sweep", len(cases))
	}

	for _, tc := range cases {
		t.Run(tc.Token, func(t *testing.T) {
			m, err := parseFrontmatter([]byte("v: " + tc.Token))
			if tc.Kind == "error" {
				if err == nil {
					t.Fatalf("PyYAML rejects %q, this accepted it as %#v", tc.Token, m["v"])
				}
				return
			}
			if err != nil {
				t.Fatalf("PyYAML resolves %q to %s %q, this failed: %v",
					tc.Token, tc.Kind, tc.Value, err)
			}
			kind, value := renderLikePython(m["v"])
			if kind == tc.Kind && value == tc.Value {
				return
			}
			// The one documented departure: Python integers are arbitrary
			// precision and Go's are not, so an integer too large for int64
			// arrives here as a float. Both are JSON *numbers*, so every schema
			// keyword in play — type, enum, const — reaches the same verdict;
			// only the digits are lost, and only past 2^63.
			if tc.Kind == "int" && kind == "float" {
				if _, err := strconv.ParseInt(tc.Value, 10, 64); errors.Is(err, strconv.ErrRange) {
					return
				}
			}
			t.Fatalf("%q: PyYAML gives %s %q, this gives %s %q",
				tc.Token, tc.Kind, tc.Value, kind, value)
		})
	}
}

// renderLikePython names and renders a resolved value the way the fixture
// generator does on the Python side, so the two can be compared as text.
func renderLikePython(v interface{}) (kind, value string) {
	switch x := v.(type) {
	case nil:
		return "null", "None"
	case bool:
		return "bool", pythonStr(x)
	case int64:
		return "int", pythonStr(x)
	case float64:
		return "float", pythonStr(x)
	case string:
		return "str", x
	}
	b, err := json.Marshal(v)
	if err != nil {
		return "unmarshalable", fmt.Sprintf("%#v", v)
	}
	return "json", string(b)
}

// TestQuotedScalarsAreAlwaysStrings pins the other half of the rule: quoting is
// how an author says "this is text", and neither implementation re-resolves it.
func TestQuotedScalarsAreAlwaysStrings(t *testing.T) {
	for _, tok := range []string{`"yes"`, `'yes'`, `"2026-01-31"`, `'1e3'`, `"017"`, `"~"`, `""`} {
		m, err := parseFrontmatter([]byte("v: " + tok))
		if err != nil {
			t.Fatalf("%s: %v", tok, err)
		}
		if _, ok := m["v"].(string); !ok {
			t.Fatalf("%s resolved to %T, want string", tok, m["v"])
		}
	}
}

// TestDatesKeepTheTextTheirAuthorWrote is the specific drift this cost the most
// to find: yaml.v3 reads 2026-1-5 as a date and would re-render it zero-padded,
// which silently repairs a value PyYAML leaves as a string and the schema's ISO
// pattern rejects.
func TestDatesKeepTheTextTheirAuthorWrote(t *testing.T) {
	for _, tc := range []struct{ in, want string }{
		{"2026-01-31", "2026-01-31"},
		{"2026-1-5", "2026-1-5"},
		{"2026-01-5", "2026-01-5"},
		{"2026-01-31T10:30:00Z", "2026-01-31T10:30:00Z"},
		{"2026-01-31 10:30:00", "2026-01-31 10:30:00"},
		{"2026-13-45", "2026-13-45"},
	} {
		m, err := parseFrontmatter([]byte("created: " + tc.in))
		if err != nil {
			t.Fatalf("%s: %v", tc.in, err)
		}
		got, ok := m["created"].(string)
		if !ok {
			t.Fatalf("%s resolved to %T, want the string it was written as", tc.in, m["created"])
		}
		if got != tc.want {
			t.Fatalf("%s became %q, want %q — a date must not be reformatted", tc.in, got, tc.want)
		}
	}
}

func TestDuplicateKeyIsRejected(t *testing.T) {
	_, err := parseFrontmatter([]byte("title: First\ntitle: Second\n"))
	if err == nil {
		t.Fatal("expected an error: a key written twice discards one of its values")
	}
}

func TestMergeKeyIsApplied(t *testing.T) {
	raw := []byte("base: &b\n  status: draft\n  title: Base\nnote:\n  <<: *b\n  title: Own\n")
	m, err := parseFrontmatter(raw)
	if err != nil {
		t.Fatal(err)
	}
	note := m["note"].(map[string]interface{})
	if note["status"] != "draft" {
		t.Fatalf("merged key missing: %#v", note)
	}
	if note["title"] != "Own" {
		t.Fatalf("an explicit key must win over a merged one, got %#v", note["title"])
	}
}

func TestFrontmatterMustBeAMapping(t *testing.T) {
	for _, raw := range []string{"- one\n- two\n", "just a scalar\n"} {
		_, err := parseFrontmatter([]byte(raw))
		if err == nil {
			t.Fatalf("expected an error for non-mapping frontmatter %q", raw)
		}
	}
}

func TestBOMIsStripped(t *testing.T) {
	data := append([]byte{0xEF, 0xBB, 0xBF}, []byte("---\ntype: note\n---\nbody\n")...)
	raw, _, ok := splitFrontmatter(data)
	if !ok {
		t.Fatal("a byte-order mark must not hide the frontmatter fence")
	}
	if string(raw) != "type: note" {
		t.Fatalf("raw = %q", raw)
	}
}

func TestRecursiveAliasDoesNotHang(t *testing.T) {
	// A self-referencing anchor is a cycle in the node graph; the walk must
	// return an error rather than run forever.
	_, err := parseFrontmatter([]byte("a: &x\n  b: *x\n"))
	if err == nil {
		t.Fatal("expected an error for a recursive alias")
	}
}
